[package]
name = "web_file_exchanger"
version = "1.0.0"
authors = ["MajorX234 <majorx234@googlemail.com>"]
edition = "2021"

[lib]
name = "web_file_exchanger"
path = "src/lib.rs"

[[bin]]
name = "web_file_exchanger_server"
path = "src/main.rs"
